future: true
syntax_highlighter: highlight.js
permalink_defaults: null
index_generator:
  path: ""
  per_page: 10
  order_by: -date
deploy:
  type: git
  repo: https://github.com/BlackCatKingdom/BlackCatKingdom.github.io.git
  branch: main
include: null
titlecase: false
date_format: YYYY-MM-DD
filename_case: 0
pagination_dir: page
tag_dir: tags
default_layout: post
time_format: HH:mm:ss
theme: stellar
source_dir: source
prismjs:
  preprocess: true
  line_number: true
  tab_replace: ""
title: 探索未知
subtitle: 探索未知
author: 陈最
keywords: 生活,技术,随笔
new_post_name: :title.md
permalink: :year/:month/:day/:title/
category_dir: categories
i18n_dir: :lang
relative_link: false
pretty_urls:
  trailing_index: true
  trailing_html: true
external_link:
  enable: true
  field: site
  exclude: ""
url: https://seekblack.cn
archive_dir: archives
per_page: 10
ignore: null
highlight:
  line_number: true
  auto_detect: false
  tab_replace: ""
  wrap: true
  hljs: false
skip_render: admin/**
public_dir: public
tag_map: null
description: 生活,技术,随笔
theme_config:
  sidebar:
    logo: /images/uploads/cat.jpg
language: zh-CN
updated_option: mtime
meta_generator: true
timezone: ""
exclude: null
render_drafts: false
category_map: null
code_dir: downloads/code
default_category: uncategorized
post_asset_folder: false
